export const authConstants = {
  LOGIN_REQUEST: "LOGIN_REQUEST",
  LOGIN_FAIL: "LOGIN_FAIL",
  LOGIN_SUCCESS: "LOGIN_SUCCESS",

  LOGOUT_REQUEST: "LOGOUT_REQUEST",
  LOGOUT_SUCCESS: "LOGOUT_SUCCESS",
  LOGOUT_FAIL: "LOGOUT_FAIL",
};

export const userConstants = {
  USER_REGISTER_REQUEST: "USER_REGISTER_REQUEST",
  USER_REGISTER_SUCCESS: "USER_REGISTER_SUCCESS",
  USER_REGISTER_FAIL: "USER_REGISTER_FAIL",
};

export const hierarchyConstants = {
  FETCH_ALL_HIERARCHIES_REQUEST: "FETCH_ALL_HIERARCHIES_REQUEST",
  FETCH_ALL_HIERARCHIES_SUCCESS: "FETCH_ALL_HIERARCHIES_SUCCESS",
  FETCH_ALL_HIERARCHIES_FAIL: "FETCH_ALL_HIERARCHIES_FAIL",
};

export const lockDoorConstants = {
  FETCH_ALL_LOCKED_DOORS_REQUEST: "FETCH_ALL_LOCKED_DOORS_REQUEST",
  FETCH_ALL_LOCKED_DOORS_SUCCESS: "FETCH_ALL_LOCKED_DOORS_SUCCESS",
  FETCH_ALL_LOCKED_DOORS_FAIL: "FETCH_ALL_LOCKED_DOORS_FAIL",

  LOCK_DOOR_REQUEST: "LOCK_DOOR_REQUEST",
  LOCK_DOOR_SUCCESS: "LOCK_DOOR_SUCCESS",
  LOCK_DOOR_FAIL: "LOCK_DOOR_FAIL",
};
export const unLockDoorConstants = {
  FETCH_ALL_UNLOCKED_DOORS_REQUEST: "FETCH_ALL_UNLOCKED_DOORS_REQUEST",
  FETCH_ALL_UNLOCKED_DOORS_SUCCESS: "FETCH_ALL_UNLOCKED_DOORS_SUCCESS",
  FETCH_ALL_UNLOCKED_DOORS_FAIL: "FETCH_ALL_UNLOCKED_DOORS_FAIL",

  UNLOCK_DOOR_REQUEST: "UNLOCK_DOOR_REQUEST",
  UNLOCK_DOOR_SUCCESS: "UNLOCK_DOOR_SUCCESS",
  UNLOCK_DOOR_FAIL: "UNLOCK_DOOR_FAIL",
};

export const productConstants = {
  GET_ALL_PRODUCT_REQUEST: "GET_ALL_PRODUCT_REQUEST",
  GET_ALL_PRODUCT_SUCCESS: "GET_ALL_PRODUCT_SUCCESS",
  GET_ALL_PRODUCT_FAIL: "GET_ALL_PRODUCT_FAIL",
};

export const pageConstants = {
  PAGE_REQUEST: "PAGE_REQUEST",
  PAGE_SUCCESS: "PAGE_SUCCESS",
  PAGE_FAIL: "PAGE_FAIL",
};

export const initialDataConstants = {
  GET_ALL_INITIAL_DATA_REQUEST: "GET_ALL_INITIAL_DATA_REQUEST",
  GET_ALL_INITIAL_DATA_SUCCESS: "GET_ALL_INITIAL_DATA_SUCCESS",
  GET_ALL_INITIAL_DATA_FAIL: "GET_ALL_INITIAL_DATA_FAIL",
};
